import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { createClient } from '@supabase/supabase-js';

// Fallback knowledge base in case the database fetch fails
const FALLBACK_KNOWLEDGE_BASE = `You are an AI assistant for Gunaseelan Jerryson's portfolio. Answer questions about Jerry naturally and helpfully.

About:
- Full Stack Developer based in Kandy, Sri Lanka
- Skilled in React, Next.js, TypeScript, Tailwind CSS, Node.js, Express.js, Supabase, Sanity.io
- Also knows Java, C#, .NET, MongoDB, SQL Server, Firebase

Experience:
- Junior Full Stack Developer at Global Island (Pvt) Ltd – LK Web Design (Nov 2025 – Feb 2026)

Contact:
- Email: jerrysonjerry1234@gmail.com
- GitHub: github.com/JerryOffiicial

Always respond in first person as Jerry. Be friendly, concise, and professional.`;

async function fetchKnowledgeBase(): Promise<string> {
  try {
    // Use server-side Supabase client with the public anon key (read-only is enough)
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseKey) {
      console.warn('Supabase env vars not set, using fallback knowledge base');
      return FALLBACK_KNOWLEDGE_BASE;
    }

    const supabase = createClient(supabaseUrl, supabaseKey);
    const { data, error } = await supabase
      .from('knowledge_base')
      .select('content')
      .order('updated_at', { ascending: false })
      .limit(1)
      .single();

    if (error || !data?.content) {
      console.warn('Could not fetch knowledge base from DB, using fallback:', error?.message);
      return FALLBACK_KNOWLEDGE_BASE;
    }

    return data.content;
  } catch (err) {
    console.warn('Error fetching knowledge base:', err);
    return FALLBACK_KNOWLEDGE_BASE;
  }
}

export async function POST(request: NextRequest) {
  try {
    const { message, history = [] } = await request.json();

    // Validate input
    if (!message || typeof message !== 'string' || !message.trim()) {
      return NextResponse.json(
        { error: 'Message is required' },
        { status: 400 }
      );
    }

    console.log('Processing chat message:', message.substring(0, 100));

    // Fetch dynamic knowledge base from Supabase
    const knowledgeBase = await fetchKnowledgeBase();

    // Initialize Google GenAI
    const ai = new GoogleGenAI({});

    // Prepare conversation history for context
    const conversationContext = history
      .filter((msg: any) => msg && msg.text && msg.sender)
      .slice(-5) // Keep last 5 messages for context
      .map((msg: any) => `${msg.sender === 'user' ? 'User' : 'Assistant'}: ${msg.text}`)
      .join('\n');

    // Create the full prompt with Jerry's context and conversation history
    const fullPrompt = `${knowledgeBase}

${conversationContext ? `Previous conversation:\n${conversationContext}\n\n` : ''}User: ${message.trim()}`;

    // Generate response
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: fullPrompt,
    });

    const aiResponse = response.text;

    if (!aiResponse) {
      console.error('No text in AI response');
      return NextResponse.json(
        { error: 'No response generated by AI service' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      response: aiResponse.trim()
    });

  } catch (error) {
    console.error('Chat API error:', {
      message: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined,
      error
    });

    if (error instanceof Error) {
      if (error.message.includes('API_KEY') || error.message.includes('authentication')) {
        return NextResponse.json(
          { error: 'Invalid API key. Please check your GEMINI_API_KEY in .env.local' },
          { status: 500 }
        );
      }
      if (error.message.includes('quota') || error.message.includes('limit')) {
        return NextResponse.json(
          { error: 'API quota exceeded. Please try again later.' },
          { status: 500 }
        );
      }
      if (error.message.includes('safety') || error.message.includes('filter')) {
        return NextResponse.json(
          { error: 'Response was filtered for safety reasons. Please try rephrasing your question.' },
          { status: 500 }
        );
      }
    }

    return NextResponse.json(
      { error: 'Internal server error. Please try again later.' },
      { status: 500 }
    );
  }
}
